[package]
name = "doot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http-types = "2.12.0"
tide = "0.16.0"
tokio = { version = "1.13.0", features = ["full"] }
